# Generated by Django 3.0.2 on 2020-02-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybasket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBasketItem',
        ),
    ]
