# Generated by Django 3.0.2 on 2020-02-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200206_1304'),
    ]

    operations = [
        migrations.RenameField('Product', 'img_url', 'image_url')
    ]
